# help(len)
# help("len")
# help(print)
# help("print")
# help(int)
# help(float)
# help(range)
# help("str")
# help(list)
# help(help)
# help("Hello".replace)
# help("Hello".split)
# help("Hello".swapcase)
help([1].extend)